CREATE TABLE CLIENTE(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
    DATA_PEDIDO TIMESTAMP,
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO(
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDO(ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
    QUANTIDADE INTEGER

);
INSERT INTO CLIENTE (NOME) VALUES ('João Silva');
INSERT INTO CLIENTE (NOME) VALUES ('Maria Santos');
INSERT INTO CLIENTE (NOME) VALUES ('Pedro Oliveira');

INSERT INTO PRODUTO (DESCRICAO, PRECO_UNITARIO) VALUES ('Camiseta', 29.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO_UNITARIO) VALUES ('Calça Jeans', 49.99);
INSERT INTO PRODUTO (DESCRICAO, PRECO_UNITARIO) VALUES ('Tênis', 79.99);

INSERT INTO PEDIDO (CLIENTE_ID, DATA_PEDIDO, TOTAL) VALUES (1, CURRENT_TIMESTAMP, 109.97);
INSERT INTO PEDIDO (CLIENTE_ID, DATA_PEDIDO, TOTAL) VALUES (2, CURRENT_TIMESTAMP, 129.98);
INSERT INTO PEDIDO (CLIENTE_ID, DATA_PEDIDO, TOTAL) VALUES (3, CURRENT_TIMESTAMP, 159.97);



